version: '3'

services:

  nginx:
    image: $NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    volumes:
     - ./:/var/www/html/
     - ./docker/nginx/app:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "81:81"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/app/Dockerfile
    volumes:
      - ./:/var/www/html/
    container_name: "${PROJECT_NAME}_frontend"


  php:
    build:
      context: .
      dockerfile: docker/php/app/Dockerfile
    volumes:
     - ./:/var/www/html/
    container_name: "${PROJECT_NAME}_php"
    environment:
         PHP_XDEBUG: 1
         PHP_XDEBUG_MODE: profile,coverage,debug
         PHP_IDE_CONFIG: serverName=my-ide
         PHP_XDEBUG_IDEKEY: my-ide
         PHP_XDEBUG_START_WITH_REQUEST: trigger
         PHP_XDEBUG_TRIGGER_VALUE: my-ide
         PHP_XDEBUG_CLIENT_HOST: 172.17.0.1 # Linux
         PHP_XDEBUG_PROFILER_OUTPUT_NAME: "%t"
         PHP_XDEBUG_LOG_LEVEL: 0

  db:
    image: $MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    volumes:
      - ./database:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
        MYSQL_DATABASE: $DB_NAME
        MYSQL_USER: $DB_USER
        MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - 8101:3306

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: "${PROJECT_NAME}_phpmyadmin"
    ports:
      - 44444:80
    environment:
      - PMA_ARBITRARY=1
