controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_page:
    path: /
    controller: App\Controller\HomeController::index
parser:
    path: /parser
    controller: App\Controller\ParserController::index
app_api:
    resource: '../src/Controller/Api'
    type: annotation